### ISSUE TITLE
Registering a User Overwrites the Test Client Added

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#1]
When you create a new in-memory user, it seems to overwrite the test user already added? 

This is I think because the password is being used to index the in memory users.

So if `tester` has password `12341234`, then if I add user "star" with the same password `12341234`, it will overwrite the test user.

**Comment by huzaifamk** [comment]
Point noted, will do some quick fixes for this.

**Comment by huzaifamk** [comment]
Going to implement the Username + Password technique for solving this issue, thanks @stravid87 for the idea!
