### ISSUE TITLE
Isse with the request URL on the layer8 Resource Server

### ISSUE THREAD

**Issue by huzaifamk** [globe-and-citizen/layer8#11]
![image](https://github.com/globe-and-citizen/layer8/assets/76698805/df565d72-e652-46cd-b094-814d5f43ccbe)

**Comment by huzaifamk** [comment]
@ternakkode if you have time, can you have a look into this issue? It looks related the the HTML templates of resource server, and you currently completed a task related to that, maybe you can solve this faster since you have recently interacted with that code. Also note that this issue is occurring on the Lightsail deployed code also, which was previously working fine, but something has happened.

**Comment by ternakkode** [comment]
this issue should be fixed by this PR: https://github.com/globe-and-citizen/layer8/pull/10

**Comment by huzaifamk** [comment]
Ok great work, I forgot to pull, thanks!
