### ISSUE TITLE
JWT Virtual Connections

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#12]
Ensure the following connections:

1) User <=> Proxy
2) Proxy <=> Middleware
3) User <=> Service Provider

**Comment by stravid87** [comment]
**Nov 20 - 26:**
1) Get all three JWTS flowing (999, 123, & 777) -- DONE

Next: 
2) Ensure that the user stays logged in as the fake name (e.g., 'HMK') even after logging in with Layer8. However, that Layer8 resource server shares metadata about the user.
3) Implement the check boxes at the authorization step.

Bonus:
Have location information from the user travel with the proxied requests IF the user approves it during Layer8 login.

**Comment by stravid87** [comment]
Team Meeting of Nov 22: Implement a Redis backend responsible for maintaining the JWTs known to the L8 Proxy.

**Comment by stravid87** [comment]
Individual Meeting Nov 27, 2023: For now, connections can likely be stored in memory (so no _need_ to implement a RedisDB).

**Comment by huzaifamk** [comment]
Actually I needed to discuss this with you, with reference to the Architecture diagram that you have made, but we will do it later, let's built up the MVP first, these things will be done later.

**Comment by stravid87** [comment]
No needs to add a Redis DB, for now, we'll keep the connections in memory.
