### ISSUE TITLE
Add service workers to WGP and ImSharer SP mocks

### ISSUE THREAD

**Issue by DeeStarks** [globe-and-citizen/layer8#137]
This is to PWAs to service provider mocks - wgp and imsharer

**Comment by DeeStarks** [comment]
- An issue has occurred when testing for the service provider mocks after registering service workers on them. It was a bit unclear at first why tests unexpectedly started failing the following message
![Image](https://github.com/user-attachments/assets/18031103-4a11-4ce8-836f-d5819df12ec2)
- Looking through this [GitHub issue's](https://github.com/cypress-io/cypress/issues/27501) comments, I came to realize that Cypress currently does not support testing on services that have service workers registered on them
- Tried the solution provided [here](https://github.com/cypress-io/cypress/issues/27501#issuecomment-1691890274), which is to unregister service workers when testing but didn't work
- Also tried [this solution](https://github.com/cypress-io/cypress/issues/27501#issuecomment-1786145001), didn't work either

**Comment by stravid87** [comment]
I'm going to pass this issue over to Marc and CF at the moment.
