### ISSUE TITLE
Make the link dynamic in the Resource Server 

### ISSUE THREAD

**Issue by huzaifamk** [globe-and-citizen/layer8#18]
Currently the links inside of these HTML templates: [User Portal Page](https://github.com/globe-and-citizen/layer8/tree/development/server/assets-v1/templates/src/pages/user_portal) & [Client Portal Page](https://github.com/globe-and-citizen/layer8/tree/development/server/assets-v1/templates/src/pages/client_portal) are hardcoded, need to convert this to take from .env dynamically.

**Comment by huzaifamk** [comment]
@NJavokhir I know this is an easy fix but I am not an expert in Frontend and I think you can do this job better!

**Comment by NJavokhir** [comment]
> @NJavokhir I know this is an easy fix but I am not an expert in Frontend and I think you can do this job better!

Okay @huzaifamk I will fix this issue.
