### ISSUE TITLE
"Don't have an account? Register" goes to wrong location

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#2]
If during the log in flow a user clicks "Don't have an account? Register" on the Layer8 login popup, it brings them to the client portal. 

Instead it should bring them to `http://localhost:5001/#register` (in other words, layer8 home page were you register).

**Comment by huzaifamk** [comment]
@stravid87 ok I will check that

**Comment by huzaifamk** [comment]
Fixed here: https://github.com/globe-and-citizen/layer8/commit/a52f94f34ba453d139a05e4e848cba06b0fd0c7d
