### ISSUE TITLE
INTERCEPTOR: For every fetch request, (line 272), a new client is created. Is this necessary? Could the client be created as a global variable and then used?

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#23]

**Comment by huzaifamk** [comment]
The thing is that I fixed this on spot when we were discussing this, and if you see here in development: https://github.com/globe-and-citizen/layer8/blob/development/interceptor/interceptor.go#L39 , it is already done, so marking this as completed and no PR for this as I fixed this on spot and is already pushed to development branch so not openeing a PR.

**Comment by stravid87** [comment]
Yup. I see it now. 
Another issue down. 
Excellent.
