### ISSUE TITLE
Making a post request to the home path of the service provider gets blocked by the proxy

### ISSUE THREAD

**Issue by DeeStarks** [globe-and-citizen/layer8#34]
I tried to make a post request to the home path of a service provider but the proxy blocks it with a `405 Method not allowed` error

```sh
curl -X POST -H "Content-Type: application/json" -d '{"hello":"world"}' http://localhost:6000/
```

![Screenshot from 2024-04-26 20-38-15](https://github.com/globe-and-citizen/layer8/assets/67328657/3f031658-055f-4f6e-b54a-09e645dedb6a)

**Comment by stravid87** [comment]
@interestIngc can you look into this one too and same thing @huzaifamk can you review / merge for her?

**Comment by DeeStarks** [comment]
I have confirmed that this now works @interestIngc
