### ISSUE TITLE
Forwarding the mp_JWT123 to the S.P.

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#36]
The goal is to unload onto the S.P. the need to maintain connections without Layer8 needing to shoulder this burden. 

However, the details of this task remain unclear to me and we should discuss further.

**Comment by huzaifamk** [comment]
As discussed, to be done in future, during re-architecting.

**Comment by stravid87** [comment]
> As discussed, to be done in future, during re-architecting.

Deal
