### ISSUE TITLE
globalThis.BACKEND Definition not used

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/layer8#38]
The global Variable BACKEND is never used. 

See here: https://github.com/globe-and-citizen/layer8/blob/541c43fc53abc5d85e6c1f4eeb15f0443cb06522/sp_mock/frontend/index.html#L14

![image](https://github.com/globe-and-citizen/layer8/assets/28951070/4ccfb587-8024-4027-a50a-12bc9447f461)

**Comment by hermannleboss** [comment]
And for a best practice, we can use Env Variable to define the location of the scpript imported. 

![image](https://github.com/globe-and-citizen/layer8/assets/28951070/87367cc6-c266-436f-9a0c-a4d23f2c9a75)

**Comment by stravid87** [comment]
> Env Variable to define the location of the scpript imported.

I'll have to check how to use '.env' with Vite. My intuition tells me it's in the config file.

**Comment by stravid87** [comment]
> The global Variable BACKEND is never used.
> 
> See here:
> 
> https://github.com/globe-and-citizen/layer8/blob/541c43fc53abc5d85e6c1f4eeb15f0443cb06522/sp_mock/frontend/index.html#L14
> 
> ![image](https://private-user-images.githubusercontent.com/28951070/292244444-4ccfb587-8024-4027-a50a-12bc9447f461.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODM3MjAsIm5iZiI6MTcwMzY4MzQyMCwicGF0aCI6Ii8yODk1MTA3MC8yOTIyNDQ0NDQtNGNjZmI1ODctODAyNC00MDI3LWE1MGEtMTJiYzk0NDdmNDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEzMjM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MjBlMGRmNGRhZDk5M2U5MmUwZGFmMTVhZjg1MWI2MmE3YmJkMTFhNjMyOGMxNTBjMmE0NThhOGU4ODEzNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F-wPztpMgZ7ON6rwxoQdbennf7AqVrBhgoLZs3pdnmg)

It's a little hacky... I'll give you that. But by using "globalThis," we really are creating a global variable. It is used in, Line30 of "server\assets-v1\cdn\interceptor\index.local.js"

**Comment by stravid87** [comment]
The build flow and use of such things as .env will improve in time.
