### ISSUE TITLE
Make the "In-Mem" implementation of the Proxy a Flag

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#40]
Currently, to run the proxy in memory, you need to comment / uncomment on lines 107 - 112.

```
	// ** USE LOCAL POSTGRES DB **
	// oauthRepository := oauthRepo.NewOauthRepository(config.DB)
	// oauthService := &oauthSvc.Service{Repo: oauthRepository}

	// ** USE THE IN MEMORY IMPLEMENTATION **
	oauthService := &oauthSvc.Service{Repo: memoryRepository}

```
This could be easily improved on by passing a flag at the time of running the program. Currently the `run_server_local` make command appears like this: 

`$cd server && go run main.go -port=5001 -jwtKey=secret -MpKey=secret -UpKey=secret -ProxyURL=http://localhost:5001`

A `db` flag could be easily added: 

`$cd server && go run main.go -port=5001 -jwtKey=secret -MpKey=secret -UpKey=secret -ProxyURL=http://localhost:5001 -db=memory`

**Comment by huzaifamk** [comment]
Good work @interestIngc , marking this as done.
