### ISSUE TITLE
Multiple client able to have same backend url

### ISSUE THREAD

**Issue by ternakkode** [globe-and-citizen/layer8#44]
Currently, the same backend URL can belong to multiple clients. Within the tunnel API, we generate a JWT token based on the backend URL. If multiple users share the same backend URL, data fetched from the database may belong to the wrong user.

One way to fix this is by adding a unique constraint for the backend URL field in the create client form.

**Comment by NJavokhir** [comment]
@ternakkode I am interested in this issue, can you provide me with description?

**Comment by ternakkode** [comment]
> @ternakkode I am interested in this issue, can you provide me with description?

updated!
