### ISSUE TITLE
Trimming / Cleaning the Folder Structure

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#47]
Now that the `proxy` and `resource_server`  are combined, do we still need the folders `proxy` & `resource_sever`?

These folders likely served as the reception points for various files (see Interceptor). 

```
# ALTERED PATH
define base64_encode
	mkdir -p ../proxy/assets/cdn/interceptor/`dirname $(1) | cut -d'/' -f3` && \
	base64 -w 0 $(1) | sed 's/^/"/' | sed 's/$$/"/' > ../server/assets-v1/cdn/interceptor/`basename $(1) | cut -d'.' -f1`.json && \
	echo "Encoded $(1) to ../server/assets-v1/cdn/interceptor/`basename $(1) | cut -d'.' -f1`.json";
endef
```

Can we now delete them? Likely we will need resurrection when we re-architect but for likely can be removed.

**Comment by huzaifamk** [comment]
Yes, those folders are no longer there, we no longer need `mkdir -p ../proxy/assets/cdn/interceptor/`dirname $(1) | cut -d'/' -f3` because there is no longer a `proxy` named folder, it is now `server` now!

**Comment by stravid87** [comment]
That's what I was thinking. 
Want to spin up a new branch, make the changes and then hit me with a merge request?

**Comment by stravid87** [comment]
Remove the utils folder as well and ensure all functionality is coming from the layer8-utils repo.

**Comment by stravid87** [comment]
@huzaifamk I'm going to close this issue and send it over to Daniel as the original author of the Makefile.
