### ISSUE TITLE
The `mapB` Interceptor Error

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#49]
In `interceptor\internals\main.go`, the .wasm will error out if the data received on line 125, `res, err := client.Do(r)` is nil. 
LINE 136: 
```
	buf := new(bytes.Buffer)
	buf.ReadFrom(res.Body)

	bufByte := buf.Bytes()

	mapB := make(map[string]interface{})
	json.Unmarshal(bufByte, &mapB)

	fmt.Println("mapB: ", mapB)
	toDecode, ok := mapB["data"].(string)
	if !ok {
		res := &utils.Response{
			Status:     500,
			StatusText: "mapB[\"data\"].(string) not 'ok'",
		}
		resByte, _ := res.ToJSON()
		return 500, resByte
	}
```

Error handling is necessary here. Otherwise, this error appears in the browser console: `mapB:  map[],  wasm_exec_v1.js:22,  panic: assignment to entry in nil map`. This panic exits the module requiring a site refresh to re-initialize the wasm module.

**Comment by DeeStarks** [comment]
@stravid87 can you provide steps to reproduce?

**Comment by stravid87** [comment]
> @stravid87 can you provide steps to reproduce?
No.... Not at this moment... Darn. It was while trying to get it to run locally. I'm playing with it again today. Let me keep this in mind and if I hit the error again, put the reproduction steps here. Posting reproduction steps: that's a habit I need to get into.

**Comment by stravid87** [comment]
@DeeStarks 
Done. In order to test this error efficiently, I added the following path to line 127 of "server\main.go",
 
```
  case path == "/error":
    handlers.TestError(w, r)
```
and in server\handlers\tunnel.go I added:

```
func TestError(w http.ResponseWriter, r *http.Request) {
	err := fmt.Errorf("This is a test error.")
	fmt.Println("Test error endpoint:", err.Error())
	http.Error(w, err.Error(), http.StatusInternalServerError)
	return
}
```
next in sp_mock/frontend/src/views/StressTest.vue I added: 


```
async function getError(){
  try {
    console.log("Error Test")
    await layer8.fetch(BackendURL + "/error", {
      method: "POST",
      headers: {
        "Content-Type": "Application/Json",
      },
      body: JSON.stringify({}),
    });
  } catch (error) {
    console.log(error);
    alert("Registration failed!");
    isRegister.value = true;
  }
}
```

(I'm going to a push branch stravid87/run_local with these changes as well)

**Comment by stravid87** [comment]
Done!
