### ISSUE TITLE
Running Make Command Creates Redundant Folder 

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#52]
@huzaifamk you were correct. If  you clone the repo, it doesn't come with the extra folders. However, running the Make command will create this folder. @DeeStarks, as the author of the Make file, can you fix this issue? I'm afraid to haha.

![Folders_L8](https://github.com/globe-and-citizen/layer8/assets/116566901/c1b7d27a-68d3-4d34-aa8a-ac9db3d6ded5)

**Comment by DeeStarks** [comment]
We can also just remove the commands. I see a `build_local_cheating` which doesn't create any sort of build variants

**Comment by stravid87** [comment]
Also done.
