### ISSUE TITLE
User Registration UI shows registration success even when the API failed

### ISSUE THREAD

**Issue by ternakkode** [globe-and-citizen/layer8#55]

**Comment by NJavokhir** [comment]
@ternakkode If you see the image below, there is "Registration failed!". Can you describe problem on your own side.

![Image](https://github.com/globe-and-citizen/layer8/assets/86225721/030d6272-f5de-4859-b06f-a558c5ea8823)

**Comment by ternakkode** [comment]
> @ternakkode If you see the image below, there is "Registration failed!". Can you describe problem on your own side.
> 
> ![Image](https://private-user-images.githubusercontent.com/86225721/331771222-030d6272-f5de-4859-b06f-a558c5ea8823.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODAxODIsIm5iZiI6MTcxNjI3OTg4MiwicGF0aCI6Ii84NjIyNTcyMS8zMzE3NzEyMjItMDMwZDYyNzItZjVkZS00ODU5LWIwNmYtYTU1OGM1ZWE4ODIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA4MjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MTJjY2MxNWE0NzI3NDMyMGEyNDRmYTUzNTExNjk3Njg3N2NhNzk0ZDYxNjhiNzNkNWQ4ZWM3MjU4ODA1MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lf0hF61Dn0b45R-42pSm36PuBqGLu_2lSVvFUWFdxus)

try to register using https://dev.layer8proxy.net

**Comment by NJavokhir** [comment]
Closed by #74
