### ISSUE TITLE
Client Login not showing any message when the api fail

### ISSUE THREAD

**Issue by ternakkode** [globe-and-citizen/layer8#56]

**Comment by stravid87** [comment]
@ternakkode I've tagged Javokhir to complete this issue. Can you provide a quick description?

**Comment by NJavokhir** [comment]
Client Login is showing when the api fail. If you show me problem which you are describing, I will fix it.

![Image](https://github.com/globe-and-citizen/layer8/assets/86225721/2136fec6-663f-4385-a0a6-0afa74510397)

**Comment by ternakkode** [comment]
> Client Login is showing when the api fail. If you show me problem which you are describing, I will fix it.
> 
> ![Image](https://private-user-images.githubusercontent.com/86225721/331771997-2136fec6-663f-4385-a0a6-0afa74510397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzk5OTMsIm5iZiI6MTcxNjI3OTY5MywicGF0aCI6Ii84NjIyNTcyMS8zMzE3NzE5OTctMjEzNmZlYzYtNjYzZi00Mzg1LWEwYTYtMGFmYTc0NTEwMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA4MjEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2OTJiNTczMmJjODIzMmEwMDJkODUyMTVlMmE3MjRmYjk4ZGI5OWEzZTRiN2MyOWRhYTljMDMyMThkNjdlMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ukYnFCJWt9fI9VvPYzLyWKiPIn2FMlC6mDYveDpock)

Try to login in https://dev.layer8proxy.net with invalid credentials
