### ISSUE TITLE
Network Error Message Response If Req/Res Stuck in Layer8 Middleware

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#62]
When a user tries to reach the S.P. backend directly without the encrypted tunnel, the Layer8 Middleware should respond with an explicit error message instead of the "no response" that currently happens. 

"400 Bad Request" or another 400 response would likely be appropriate.

**Comment by DeeStarks** [comment]
Or rather return the data unencrypted? This will give the service provider the option to encrypt transmitted data or not (i.e. if they use `layer8.fetch` the data is encrypted, and if they choose to use `window.fetch` for some requests, our implementation should not block them, it should return the data unencrypted)
I thought we had this in place earlier on in the project

**Comment by stravid87** [comment]
> Or rather return the data unencrypted? This will give the service provider the option to encrypt transmitted data or not (i.e. if they use `layer8.fetch` the data is encrypted, and if they choose to use `window.fetch` for some requests, our implementation should not block them, it should return the data unencrypted) I thought we had this in place earlier on in the project

I remember we had something to the effect of header `x-tunnel`. I do not remember the exact details. At this time, you can implement the simplest solution if you find yourself getting hung up. At this time the functionality is primarily for testing during development (given that we wont have "real" clients at present).
