### ISSUE TITLE
Remove All Hard Coded Address Configurations

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#97]
This issue goes along with issue #88

 In `./server/tunnel.go`, there is the line:

`mpJWT, err := utilities.GenerateStandardToken(os.Getenv("MP_123_SECRET_KEY"))`

Just below it is the line: 

`backendURL := fmt.Sprintf("http://%s", backend) //TODO`

Obviously, if one can come from the .env, both can. 

There are similar gotchas through out the project such as this.

**Comment by huzaifamk** [comment]
This has been removes, so marking this as closed.
